export const MOCK_GENRES = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Horror",
  "Historical Fiction",
  "Non-Fiction",
  "Biography",
  "Self-Help",
  "Graphic Novel",
  "Young Adult",
  "Children's",
  "Adventure",
  "Drama",
  "Poetry",
  "Classic",
  "Dystopian",
  "Crime",
  "Humor",
  "Spirituality",
  "Contemporary",
  "Paranormal",
  "LGBTQ+",
  "Western",
  "Political",
  "Cooking",
  "Art",
  "Travel",
  "Memoir",
  "Science",
  "Business",
  "Education",
  "Technology",
] as const;

export type MockGenre = (typeof MOCK_GENRES)[number];
