import type { Metadata } from 'next';
import { Sidebar } from '../../components/common/sidebar/Sidebar';
import '../../styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* BACKGROUND COLOR */}
      <div className="fixed inset-0 grid grid-cols-2">
        <div className="bg-secondary" />
      </div>
      <section className="relative mx-auto grid min-h-dvh max-w-screen-sm grid-cols-[auto_1fr]">
        <Sidebar />
        <main className="bg-background pt-16">{children}</main>
      </section>
    </>
  );
}
